# Generated by Django 4.1 on 2022-09-10 14:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('slot', models.PositiveSmallIntegerField(choices=[(1, '10:00-10:30'), (2, '10:30-11:00'), (3, '11:00-11:30'), (4, '11:30-12:00'), (5, '12:00-12:30'), (6, '12:30-13:00'), (7, '13:00-13:30'), (8, '13:30-14:00'), (9, '14:00-14:30'), (10, '14:30-15:00'), (11, '15:00-15:30'), (12, '15:30-16:00'), (13, '16:00-16:30'), (14, '16:30-17:00'), (15, '17:00-17:30'), (16, '17:30-18:00'), (16, '18:00-18:30')])),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_slot', to='stations.station', verbose_name='station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_slot', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'unique_together': {('station', 'date', 'slot')},
            },
        ),
    ]
