# Generated by Django 4.1 on 2022-09-10 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_slot',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
