# Generated by Django 4.1 on 2022-09-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_time_slot_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time_slot',
            options={'ordering': ['-created']},
        ),
    ]
